### ISSUE TITLE
Is this code complete?

### ISSUE THREAD

**Issue by HeadReaper-hc** [eowjd0512/VITAMIN-E#2]
Hi,
     I only see feature extraction and feature track in the code, so is this code complete?

**Comment by eowjd0512** [comment]
I fixed several tiny problems in the feature extraction and tracking modules, and you can see this code can make an initial structure after the initialization step.
However, there is a problem still in the tracking module that some local features fall into the same local extrema during hill climbing even after adapting the dominant flow.
(This local extrema problem is mentioned at the paper, page 3, above Section 3.
"**Note that extrema tracking can easily fall into local solutions** because there are many extrema in image curvature and it is almost impossible to distinguish them without any descriptors. However, the prediction according to the dominant flow boosts the accuracy of extrema tracking and enables it to approach the optimal solution.")

In addition, since the initial tracking position of the local features depends on the dominant flow, which is based on the 2D affine transformation, tracking does not work well in a scene where a 3D structure captured (too close) with large disparity.

**Comment by HeadReaper-hc** [comment]
@eowjd0512 
Thank you for reply with so much details, which is really helpful for me.
